### PR TITLE
update to angular 12

### PR DESCRIPTION
**Pull request by nema1012**

### CODE REVIEW

**Comment by omikolaj** [comment]
Could this be merged soon?

**Comment by kharratahmed** [comment]
Any news here ? Could this be merged soon?

**Review by guilhermebc — APPROVED** [review]

**Comment by inexuscore** [comment]
Is this repo actively maintained? I'm using this in several projects and I'm stuck updating Angular to v13, peer dependency conflicts. Any idea when we'll get proper maintenance to move to Angular 13? Thank you.

**Comment by lukaszbachman** [comment]
Same here. I kindly request accepting this PR.

**Comment by Cordobo** [comment]
@nema1012 

Thanks for your time and effort, unfortunately I had to reintegrate your changes manually because of github being offended by a package-lock.json file :(

Version 12 for angular 12 has been released with your code changes.

**Comment by inexuscore** [comment]
Thank you for your time and effort. Can we use this with Angular 13 now?

**Comment by Cordobo** [comment]
Just as a note for those coming along, the latest version of angularx-qrcode supports angular 13.

**Pull request closed without merging**
