### PR TITLE
Angular 17 Update

### PR DESCRIPTION
**Pull request by Muehli25**
I updated the library to angular 17 and also utilise newer versions for some sub dependencies.

### CODE REVIEW

**Comment by ravicini** [comment]
Did the same update, and verified it with the demo app.
My Changes were almost similar, except for a newer minor version which was released between our updates.

Verified the update with the demo app and everything seems to work.

**Comment by zamecki** [comment]
Hi there! Any plans on completing this?

**Comment by ravicini** [comment]
@Cordobo can we support in any way?

**Review by PeterSimonis — APPROVED** [review]

**Comment by PeterSimonis** [comment]
Another week and @Cordobo remains silent...

**Comment by PeterSimonis** [comment]
Hello Andreas (@Cordobo), 
Do you think you might have time to merge this PR and create an Angular 17 compatible version?
Or do we need to fork the repo and consider this project ended?
I realy enjoyed using this library so it would be a shame if I had to integrate some other package.
Looks like all the work has been done and verified.
I look forward to hearing from you.
Peter

**Comment by Cordobo** [comment]
Sorry @all

It's been a tough ride in the last weeks with my day job which took all of my resources.

Thanks to @Muehli25 PR and @PeterSimonis review we have a new release called angularx-qrcode 17.

**Pull request merged**
