### PR TITLE
Updated peer dependencies to accept all version of Angular up to 7.2.x

### PR DESCRIPTION
**Pull request by hebra**
Updated peer dependencies to accept all version of Angular up to 7.2.x

### CODE REVIEW

**Comment by DavidBowdoin** [comment]
Can the package be set to accept Angular 7.x.x

**Comment by hebra** [comment]
I was thinking about this but came to the conclusion that it is not a good idea as Angular is known to sometimes introduce breaking changes within minor release.
Therefore I'd think we keep it as it is and we will change to <7.4 as soon as Angular 7.3.x is released and tested.

**Comment by Cordobo** [comment]
Hello @hebra 

thanks for your PR. Could you please open yur PR against the develop-branch? I will add the information to the Readme in a contribution section. Sorry for the inconveniences :)

**Comment by hebra** [comment]
No worries. This has been done now. There should be a new PR for the dev branch.

**Pull request closed without merging**
