### PR TITLE
Fix issue #211 - move @types/qrcode back to devDependencies

### PR DESCRIPTION
**Pull request by jamesanderson9182**
This should fix the issue described in #211. This is my first time submitting a PR to an open source repository so let me know if there's anything else you need me to do.

### CODE REVIEW

**Comment by sam-s4s** [comment]
Hopefully this gets merged and built soon, it's being such a pain for us! <3

**Comment by JAntonioCV** [comment]
Hello, I am presenting the same error in Angular 15, do you know if the conflict has already been resolved?

**Comment by sam-s4s** [comment]
@Cordobo I don't suppose you could help push this one though? <3

**Comment by JAntonioCV** [comment]
@sam-s4s En otra app de codigo que QR que nesecitaba generar tenia una dependencia de types/node una vez actualizada la libreria los errores han desaparecido, posiblemente tu necesites actualizar types/node y probar nuevamente

**Comment by sam-s4s** [comment]
> @sam-s4s In another code library that QR needed to generate had a dependency on types/node once the library was updated the errors have disappeared, possibly you need to update types/node and try again

This did help fix one of the issues we were having, thank you.

Some of the errors are gone, but some still remain - for example, the setTimeout still returning a NodeJS.Timeout instead of a number :(

I think the best solution is still to never include the node types in the "dependencies" section, and always only include it in the "devDependencies" section.

At the very least VS Code does not like it.

**Comment by JAntonioCV** [comment]
I solved this error I was going to try this library but I haven't had time to see if the errors were resolved just by updating the type/node but I haven't had the same time this is useful for future people who have the same error and look for a thread because that was my case

**Comment by Cordobo** [comment]
@jamesanderson9182 

thanks for your PR, I merged it right now and released 16.0.1. Thanks for your contribution and sorry for the delay

**Comment by JAntonioCV** [comment]
@Cordobo thanks

**Pull request merged**
